services:
  mantisbase:
    build:
      context: .
      dockerfile: Dockerfile
    image: mantisbase:latest
    restart: unless-stopped
    ports:
      - "7070:80"
    volumes:
      - ./data:/mb/data
      - ./www:/mb/public
      - ./scripts:/mb/scripts